### ISSUE TITLE
The Update button in customers Issues

### ISSUE THREAD

**Issue by esraaelkholy** [mohamed-moanis/AGEAS-eg#10]
![phone number delted](https://cloud.githubusercontent.com/assets/11458896/7547531/897d55fa-f5ef-11e4-840d-b8a568b934c3.jpg)
1-the update button in customers allows letters for telephone , and cash can be zero
2- it accepts empty rows for name and telephone , while cash doesn't change if it was an empty entery
3- cash accepts Zero if zero was written while remain  the previous value if it was left null
4- it thows an exception if you deleted a phone number and clicked update giving the above  issue

**Comment by mmoanis** [comment]
The point is, we have an entry in the database with phone number = 0
UI must check the validity of a phone number, use regex

**Comment by MichaelSedrak** [comment]
1, 2, 3 are solved.

for number 4 the problem is the telephone att. is unique so it doesn't accept duplicates.
