### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by MaramAlaa** [mohamed-moanis/AGEAS-eg#5]
- correct username admin but with extra white space
- give error msg

**Comment by mmoanis** [comment]
white spaces are allowed both at the front and end?
or just at the end?

**Comment by mmoanis** [comment]
not sure if we should allow whitespaces or not

**Comment by MaramAlaa** [comment]
i tried at the end .. when u log in to any site and type spaces  (for ex: fb) no error appears

**Comment by mmoanis** [comment]
check the commit, I will close the issue. Reopen if still not fixed
